"""Initial migration: Add Analysis, BinDetection, and Artifact tables

Revision ID: 1a4ae09f46e4
Revises: 
Create Date: 2025-12-23 21:38:35.879890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4ae09f46e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_type', sa.Enum('IMAGE', 'VIDEO', name='inputtypeenum'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('EMPTY', 'HALF', 'FULL', 'NO_BIN_DETECTED', name='filllevelenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bins_detected', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('debug_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_input_type'), 'analyses', ['input_type'], unique=False)
    op.create_index(op.f('ix_analyses_started_at'), 'analyses', ['started_at'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('OVERLAY_IMAGE', 'CROPPED_BIN', 'METADATA_JSON', 'ORIGINAL_FILE', name='artifacttypeenum'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('bin_index', sa.Integer(), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_analysis_id'), 'artifacts', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_artifacts_type'), 'artifacts', ['type'], unique=False)
    op.create_table('bin_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('bin_index', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=False),
    sa.Column('bbox_y1', sa.Integer(), nullable=False),
    sa.Column('bbox_x2', sa.Integer(), nullable=False),
    sa.Column('bbox_y2', sa.Integer(), nullable=False),
    sa.Column('fill_level', sa.Enum('EMPTY', 'HALF', 'FULL', 'NO_BIN_DETECTED', name='filllevelenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('classifier_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_detections_analysis_id'), 'bin_detections', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bin_detections_analysis_id'), table_name='bin_detections')
    op.drop_table('bin_detections')
    op.drop_index(op.f('ix_artifacts_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_analysis_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_started_at'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_input_type'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
