"""Add batch upload tables (BatchAnalysis, BatchItem) and update Artifact

Revision ID: 9626bc482653
Revises: 1a4ae09f46e4
Create Date: 2025-12-23 21:52:06.483597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9626bc482653'
down_revision: Union[str, Sequence[str], None] = '1a4ae09f46e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('status_counts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_analyses_batch_id'), 'batch_analyses', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batch_analyses_created_at'), 'batch_analyses', ['created_at'], unique=False)
    op.create_table('batch_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('EMPTY', 'HALF', 'FULL', 'NO_BIN_DETECTED', name='filllevelenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bins_detected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_items_batch_id'), 'batch_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_items_status'), 'batch_items', ['status'], unique=False)
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('analysis_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_artifacts_batch_item_id'), ['batch_item_id'], unique=False)
        batch_op.create_foreign_key('fk_artifacts_batch_item_id', 'batch_items', ['batch_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_artifacts_batch_item_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_artifacts_batch_item_id'))
        batch_op.alter_column('analysis_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.drop_column('batch_item_id')

    op.drop_index(op.f('ix_batch_items_status'), table_name='batch_items')
    op.drop_index(op.f('ix_batch_items_batch_id'), table_name='batch_items')
    op.drop_table('batch_items')
    op.drop_index(op.f('ix_batch_analyses_created_at'), table_name='batch_analyses')
    op.drop_index(op.f('ix_batch_analyses_batch_id'), table_name='batch_analyses')
    op.drop_table('batch_analyses')
    # ### end Alembic commands ###
